pipeline {
    agent{

      docker {
        image 'python:3.11.0-slim'
      }
    }

    stages {
        stage('Build') {

          when{
            changeset "**/vote/**"
          }
            steps {
                echo 'Compiling vote app...'
                dir('vote') {
                  sh 'pip install -r requirements.txt'
                }
            }
        }
        stage('Test') {
          when{
            changeset "**/vote/**"
          }
            steps {
                echo 'Running Unit Tests on vote app...'
                dir('vote'){
                  sh 'nosetests -v'
                }
            }
        }
    }
        post{
          always{
            echo 'Building multibranch pipeline for vote is completed..'
          }
          failure{
            slackSend (channel: "training", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open)")
          }
          success{
            slackSend (channel: "training", message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open)")
          }
        }
}
