version: "3.3"

volumes:
  db-data:
     
networks:
  instavote:
    driver: bridge          

services:

  vote:
    image: rotimi98/vote:latest
    ports:
    - 6002:80
    depends_on:
    - redis
    networks:
    - instavote

  redis:
    image: redis:alpine
    networks:
    - instavote

  db:
    image: postgres:9.4
    volumes:
    - "db-data:/var/lib/postgresql/data"
    networks:
    - instavote
    environment:
      # POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust

  result:
    image: rotimi98/result:latest
    ports:
    - 6001:4000
    depends_on:
    - db
    networks:
    - instavote

  worker:
    image: rotimi98/worker:latest
    depends_on:
    - redis
    - db
    networks:
    - instavote
